name: generate iso calendar

on:
  schedule:
    - cron: "0 */1 * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main
    
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: lowlighter/metrics@latest
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/metrics.plugin.isocalendar.svg
          
          
      - name: push metrics.plugin.isocalenda.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


