name: generate iso calendar

on:
  schedule:
    - cron: "0 */1 * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Full-year calendar
      uses: lowlighter/metrics@latest
      with:
        filename: dist/metrics.plugin.isocalendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year



